name: CT Model Deploy

on:
  issues:
    types: [closed]

jobs:
  add-comment:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'ct')
    steps:
      - name: Get current timestamp
        id: timestamp
        run: |
          echo "timestamp=$(TZ=":Asia/Seoul" date -R|sed 's/.....$//')" >> $GITHUB_ENV
      - name: Add Comment
        run: |
          if [ "$STATE_REASON" == "completed" ] || [ "$SENDER" != "github-actions" ]; then
            gh issue comment "$NUMBER" --body "CT Model Deploy was approved at ${{env.timestamp}}."
          else
            gh issue comment "$NUMBER" --body "CT Model Deploy was disapproved at ${{env.timestamp}}."
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          SENDER: ${{ github.event.sender.login }}
          NUMBER: ${{ github.event.issue.number }}
          STATE_REASON: ${{ github.event.issue.state_reason }}
  add-tags:
    needs: add-comment
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get SourceVersion
        id: sourceversion
        run: |
          echo "sourceversion=$(git describe --tags --abbrev=0 | grep -Eo '[0-9]{1,}.[0-9]{1,}.[0-9]{1,}')" >> $GITHUB_ENV
      - name: Get ModelName
        id: modelname
        run: |
          echo "modelname=$(echo "${{ github.event.issue.body }}" | grep -oP 'model name :\s*\K\w+')" >> $GITHUB_ENV
      - name: Get ModelVersion
        id: modelversion
        run: |
          echo "modelversion=$(cat ./versions/version)"  >> $GITHUB_ENV
      - name: test env
        run: |
          env | grep model
      - uses: actions/github-script@v7
        name: Create tag
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${{env.sourceversion}}-model-${{env.modelversion}}`,
              sha: context.sha,
            })
      - name: Add Comment
        run: |
          gh issue comment "${{ github.event.issue.number }}" --body "${{env.sourceversion}}-model-${{env.modelversion}} tagging was completed"